package com.cactus.app.ui.player.slides
import androidx.compose.animation.core.animateFloatAsState; import androidx.compose.animation.core.tween
import androidx.compose.foundation.background; import androidx.compose.foundation.border; import androidx.compose.foundation.clickable; import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.layout.*; import androidx.compose.foundation.lazy.LazyColumn; import androidx.compose.foundation.lazy.items; import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons; import androidx.compose.material.icons.filled.Add; import androidx.compose.material.icons.filled.Close; import androidx.compose.material.icons.filled.MoreVert; import androidx.compose.material.icons.filled.Note
import androidx.compose.material3.*; import androidx.compose.runtime.*; import androidx.compose.ui.Alignment; import androidx.compose.ui.Modifier; import androidx.compose.ui.draw.clip; import androidx.compose.ui.draw.scale; import androidx.compose.ui.text.font.FontWeight; import androidx.compose.ui.text.style.TextOverflow; import androidx.compose.ui.unit.dp; import androidx.compose.ui.unit.sp
import androidx.hilt.navigation.compose.hiltViewModel; import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.cactus.app.data.model.Note; import com.cactus.app.ui.components.PaginationDots; import com.cactus.app.ui.components.PlayerDock; import com.cactus.app.ui.components.PlayerHeader; import com.cactus.app.ui.player.LocalPlayerHolder; import com.cactus.app.ui.theme.CactusColors; import com.cactus.app.util.TimeUtils
@Composable
fun NotesSlide(videoId: Long?, onDismiss: () -> Unit, viewModel: NotesViewModel = hiltViewModel()) {
    val holder = LocalPlayerHolder.current; val playerState by holder.state.collectAsStateWithLifecycle()
    LaunchedEffect(videoId) { videoId?.let { viewModel.setActiveVideo(it) } }
    val notes by viewModel.notes.collectAsStateWithLifecycle(); var showAddModal by remember { mutableStateOf(false) }; var openMenuId by remember { mutableStateOf<Long?>(null) }
    val expanded = remember { mutableStateMapOf<Long, Boolean>() }
    val progressFraction = if (playerState.durationMs > 0) (playerState.currentPositionMs.toFloat() / playerState.durationMs.toFloat()).coerceIn(0f, 1f) else 0f
    Column(modifier = Modifier.fillMaxSize().background(CactusColors.White)) {
        PlayerHeader(title = "My Notes", subtitle = "Timestamped Notes", onDismiss = onDismiss, rightAction = { Icon(Icons.Filled.Add, contentDescription = "Add note", tint = CactusColors.Neutral700, modifier = Modifier.size(22.dp).clickable(interactionSource = remember { MutableInteractionSource() }, indication = null, onClick = { showAddModal = true })) })
        if (notes.isEmpty()) { Box(Modifier.fillMaxWidth().weight(1f), contentAlignment = Alignment.Center) { Column(horizontalAlignment = Alignment.CenterHorizontally) { Box(Modifier.size(64.dp).clip(RoundedCornerShape(50)).background(CactusColors.Neutral100), contentAlignment = Alignment.Center) { Icon(Icons.Filled.Note, contentDescription = null, tint = CactusColors.Neutral400, modifier = Modifier.size(28.dp)) }; Spacer(Modifier.height(20.dp)); Text("No notes yet", fontSize = 16.sp, fontWeight = FontWeight.Bold, color = CactusColors.Neutral800); Spacer(Modifier.height(8.dp)); Text("Tap + to add a note", fontSize = 12.sp, color = CactusColors.Neutral500) } } }
        else { LazyColumn(modifier = Modifier.fillMaxWidth().weight(1f).padding(horizontal = 20.dp, vertical = 12.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { items(notes) { note -> Box { Column(modifier = Modifier.fillMaxWidth().clip(RoundedCornerShape(12.dp)).border(1.dp, CactusColors.Neutral100, RoundedCornerShape(12.dp)).clickable(interactionSource = remember { MutableInteractionSource() }, indication = null) { expanded[note.id] = !(expanded[note.id] == true) }.padding(12.dp)) { Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.SpaceBetween, modifier = Modifier.fillMaxWidth()) { Row(verticalAlignment = Alignment.CenterVertically) { Icon(Icons.Filled.Note, contentDescription = null, tint = CactusColors.Neutral400, modifier = Modifier.size(12.dp)); Spacer(Modifier.width(6.dp)); Text("${TimeUtils.formatDuration(note.positionMs)} - ${note.wordCount} ${if (note.wordCount == 1) "Word" else "Words"}", fontSize = 10.sp, fontWeight = FontWeight.Bold, color = CactusColors.Neutral400, letterSpacing = 1.sp) }; Box(Modifier.size(24.dp).clip(RoundedCornerShape(50)).clickable(interactionSource = remember { MutableInteractionSource() }, indication = null) { openMenuId = if (openMenuId == note.id) null else note.id }, contentAlignment = Alignment.Center) { Icon(Icons.Filled.MoreVert, contentDescription = null, tint = CactusColors.Neutral400, modifier = Modifier.size(12.dp)) } }; Spacer(Modifier.height(6.dp)); Text(note.text, fontSize = 14.sp, fontWeight = FontWeight.Medium, color = CactusColors.Neutral800, maxLines = if (expanded[note.id] == true) Int.MAX_VALUE else 2, overflow = TextOverflow.Ellipsis) }; DropdownMenu(expanded = openMenuId == note.id, onDismissRequest = { openMenuId = null }, modifier = Modifier.width(112.dp)) { DropdownMenuItem(text = { Text("Delete", fontSize = 12.sp, fontWeight = FontWeight.Medium, color = CactusColors.Red500) }, onClick = { viewModel.deleteNote(note.id); openMenuId = null }) } } } } }
        PlayerDock(progressFraction = progressFraction, currentTimeLabel = TimeUtils.formatDuration(playerState.currentPositionMs), totalTimeLabel = TimeUtils.formatDuration(playerState.durationMs), centerButtonLabel = if (playerState.isPlaying) "Pause" else "Play", isPlaying = playerState.isPlaying, onCenterClick = { holder.togglePlayPause() }, onSeekBack = { holder.seekRelative(-15_000L) }, onSeekForward = { holder.seekRelative(15_000L) })
        PaginationDots(activeIndex = 3)
    }
    if (showAddModal && videoId != null) { AddNoteModal(currentTimeLabel = TimeUtils.formatDuration(playerState.currentPositionMs), onDismiss = { showAddModal = false }, onSave = { text -> viewModel.createNote(videoId, text, playerState.currentPositionMs); showAddModal = false }) }
}
@Composable
private fun AddNoteModal(currentTimeLabel: String, onDismiss: () -> Unit, onSave: (String) -> Unit) {
    var text by remember { mutableStateOf("") }
    Box(Modifier.fillMaxSize().background(CactusColors.Black.copy(alpha = 0.4f)).clickable(interactionSource = remember { MutableInteractionSource() }, indication = null, onClick = onDismiss), contentAlignment = Alignment.Center) {
        val scale by animateFloatAsState(1f, tween(350), label = "modal")
        Surface(shape = RoundedCornerShape(16.dp), color = CactusColors.White, modifier = Modifier.padding(horizontal = 20.dp).fillMaxWidth().scale(scale).clickable(interactionSource = remember { MutableInteractionSource() }, indication = null, onClick = {}).padding(20.dp)) {
            Column { Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.SpaceBetween, modifier = Modifier.fillMaxWidth()) { Column { Text("Add Note", fontSize = 18.sp, fontWeight = FontWeight.Bold, color = CactusColors.Black); Text("Note for $currentTimeLabel", fontSize = 11.sp, color = CactusColors.Neutral400, fontWeight = FontWeight.Medium) }; Icon(Icons.Filled.Close, contentDescription = null, tint = CactusColors.Neutral400, modifier = Modifier.size(24.dp).clickable(interactionSource = remember { MutableInteractionSource() }, indication = null, onClick = onDismiss)) }; Spacer(Modifier.height(16.dp)); OutlinedTextField(value = text, onValueChange = { text = it }, placeholder = { Text("Write your note here...", fontSize = 14.sp, color = CactusColors.Neutral500) }, shape = RoundedCornerShape(8.dp), colors = OutlinedTextFieldDefaults.colors(focusedBorderColor = CactusColors.Black, unfocusedBorderColor = CactusColors.Neutral200, unfocusedContainerColor = CactusColors.Neutral100), modifier = Modifier.fillMaxWidth().heightIn(min = 120.dp)); Spacer(Modifier.height(16.dp)); Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { Button(onClick = onDismiss, shape = RoundedCornerShape(8.dp), colors = ButtonDefaults.buttonColors(containerColor = CactusColors.Neutral100, contentColor = CactusColors.Neutral700), modifier = Modifier.weight(1f)) { Text("Cancel", fontSize = 14.sp, fontWeight = FontWeight.Bold) }; Button(onClick = { if (text.isNotBlank()) onSave(text.trim()) }, shape = RoundedCornerShape(8.dp), colors = ButtonDefaults.buttonColors(containerColor = CactusColors.Black, contentColor = CactusColors.White), modifier = Modifier.weight(1f)) { Text("Save Note", fontSize = 14.sp, fontWeight = FontWeight.Bold) } } }
        }
    }
}
