package com.cactus.app.ui.home
import android.content.Intent; import android.net.Uri; import android.provider.Settings; import android.widget.Toast
import androidx.activity.compose.rememberLauncherForActivityResult; import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background; import androidx.compose.foundation.clickable; import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.layout.*; import androidx.compose.foundation.lazy.LazyColumn; import androidx.compose.foundation.lazy.LazyRow; import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape; import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons; import androidx.compose.material.icons.filled.ChevronRight; import androidx.compose.material.icons.filled.Close; import androidx.compose.material.icons.filled.MusicVideo; import androidx.compose.material.icons.filled.Notifications; import androidx.compose.material.icons.filled.Refresh; import androidx.compose.material.icons.filled.Search; import androidx.compose.material.icons.filled.Settings; import androidx.compose.material.icons.filled.Tune; import androidx.compose.material.icons.filled.VideoFile
import androidx.compose.material3.*; import androidx.compose.runtime.*; import androidx.compose.ui.Alignment; import androidx.compose.ui.Modifier; import androidx.compose.ui.draw.clip; import androidx.compose.ui.platform.LocalContext; import androidx.compose.ui.text.font.FontWeight; import androidx.compose.ui.text.style.TextAlign; import androidx.compose.ui.text.style.TextOverflow; import androidx.compose.ui.unit.dp; import androidx.compose.ui.unit.sp
import androidx.hilt.navigation.compose.hiltViewModel; import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.cactus.app.data.model.Video; import com.cactus.app.data.repository.VideoFilter; import com.cactus.app.ui.theme.CactusColors; import com.cactus.app.util.FileSize
@Composable
fun HomeScreen(onVideoClick: (Video) -> Unit, onSettingsClick: () -> Unit, viewModel: HomeViewModel = hiltViewModel()) {
    val context = LocalContext.current; val uiState by viewModel.uiState.collectAsStateWithLifecycle(); val videos by viewModel.videos.collectAsStateWithLifecycle()
    val permissionLauncher = rememberLauncherForActivityResult(ActivityResultContracts.RequestMultiplePermissions()) { grants -> val anyGranted = grants.values.any { it }; val activity = context.findActivity(); val canStillAsk = activity?.let { act -> viewModel.requiredPermissions().any { p -> act.shouldShowRequestPermissionRationale(p) } } ?: true; viewModel.onPermissionResult(anyGranted, canStillAsk) }
    LaunchedEffect(uiState.permissionState) { if (uiState.permissionState == PermissionState.UNKNOWN) permissionLauncher.launch(viewModel.requiredPermissions()) }
    val lifecycleOwner = androidx.lifecycle.compose.LocalLifecycleOwner.current
    androidx.compose.runtime.DisposableEffect(lifecycleOwner) { val observer = androidx.lifecycle.LifecycleEventObserver { _, event -> if (event == androidx.lifecycle.Lifecycle.Event.ON_RESUME && uiState.permissionState == PermissionState.GRANTED && !uiState.isScanning) viewModel.scanMediaStore() }; lifecycleOwner.lifecycle.addObserver(observer); onDispose { lifecycleOwner.lifecycle.removeObserver(observer) } }
    val filters = listOf(VideoFilter.NEW to "New", VideoFilter.LARGE_TO_SMALL to "Large to small", VideoFilter.SMALL_TO_LARGE to "Small to large", VideoFilter.WITH_SUBTITLES to "Subtitle generated", VideoFilter.WITHOUT_SUBTITLES to "Subtitle not generated")
    var showFilters by remember { mutableStateOf(false) }
    Column(modifier = Modifier.fillMaxSize().background(CactusColors.White).statusBarsPadding()) {
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.SpaceBetween, modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 16.dp)) {
            Column { Text("Cactus", fontSize = 24.sp, fontWeight = FontWeight.ExtraBold, color = CactusColors.Black, letterSpacing = (-0.5).sp); Text("Learn English by listening", fontSize = 13.sp, fontWeight = FontWeight.Medium, color = CactusColors.Neutral500, modifier = Modifier.padding(top = 4.dp)) }
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                Box(modifier = Modifier.size(40.dp).clip(CircleShape).background(CactusColors.Neutral100).clickable(interactionSource = remember { MutableInteractionSource() }, indication = null, onClick = {}), contentAlignment = Alignment.Center) { Icon(Icons.Filled.Notifications, contentDescription = "Notifications", tint = CactusColors.Neutral700, modifier = Modifier.size(18.dp)) }
                Box(modifier = Modifier.size(40.dp).clip(CircleShape).background(CactusColors.Neutral100).clickable(interactionSource = remember { MutableInteractionSource() }, indication = null, onClick = onSettingsClick), contentAlignment = Alignment.Center) { Icon(Icons.Filled.Settings, contentDescription = "Settings", tint = CactusColors.Neutral700, modifier = Modifier.size(18.dp)) }
            }
        }
        Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp).padding(bottom = 8.dp).clip(RoundedCornerShape(50)).background(CactusColors.Neutral100).padding(horizontal = 16.dp, vertical = 10.dp)) {
            Icon(Icons.Filled.Search, contentDescription = null, tint = CactusColors.Neutral500, modifier = Modifier.size(16.dp)); Spacer(Modifier.width(10.dp))
            androidx.compose.foundation.text.BasicTextField(value = uiState.searchQuery, onValueChange = { viewModel.setSearchQuery(it) }, singleLine = true, textStyle = androidx.compose.ui.text.TextStyle(fontSize = 14.sp, fontWeight = FontWeight.Medium, color = CactusColors.Neutral900), cursorBrush = androidx.compose.ui.graphics.SolidColor(CactusColors.Black), modifier = Modifier.weight(1f), decorationBox = { inner -> if (uiState.searchQuery.isEmpty()) { Text("Search videos...", fontSize = 14.sp, fontWeight = FontWeight.Medium, color = CactusColors.Neutral500) }; inner() })
            if (uiState.searchQuery.isNotEmpty()) { Icon(Icons.Filled.Close, contentDescription = "Clear", tint = CactusColors.Neutral500, modifier = Modifier.size(16.dp).clickable(interactionSource = remember { MutableInteractionSource() }, indication = null, onClick = { viewModel.setSearchQuery("") })) }
            else { Icon(Icons.Filled.Tune, contentDescription = "Toggle filters", tint = if (showFilters) CactusColors.Black else CactusColors.Neutral500, modifier = Modifier.size(18.dp).clickable(interactionSource = remember { MutableInteractionSource() }, indication = null, onClick = { showFilters = !showFilters })) }
        }
        if (showFilters) { LazyRow(horizontalArrangement = Arrangement.spacedBy(8.dp), contentPadding = PaddingValues(horizontal = 16.dp), modifier = Modifier.fillMaxWidth().padding(bottom = 8.dp)) { items(filters) { (filter, label) -> val active = filter == uiState.selectedFilter; Box(modifier = Modifier.clip(RoundedCornerShape(50)).background(if (active) CactusColors.Black else CactusColors.Neutral100).clickable(interactionSource = remember { MutableInteractionSource() }, indication = null) { viewModel.setSelectedFilter(filter) }.padding(horizontal = 14.dp, vertical = 6.dp)) { Text(label, fontSize = 12.sp, fontWeight = if (active) FontWeight.Bold else FontWeight.SemiBold, color = if (active) CactusColors.White else CactusColors.Neutral700) } } } }
        HorizontalDivider(thickness = 1.dp, color = CactusColors.Neutral100)
        when {
            uiState.permissionState == PermissionState.UNKNOWN -> { Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) { CircularProgressIndicator(color = CactusColors.Black, strokeWidth = 2.dp, modifier = Modifier.size(40.dp)) } }
            uiState.permissionState == PermissionState.PERMANENTLY_DENIED -> { Column(Modifier.fillMaxSize().padding(32.dp), horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.Center) { Box(Modifier.size(64.dp).clip(CircleShape).background(CactusColors.Neutral100), contentAlignment = Alignment.Center) { Icon(Icons.Filled.MusicVideo, contentDescription = null, tint = CactusColors.Red500, modifier = Modifier.size(28.dp)) }; Spacer(Modifier.height(20.dp)); Text("Manual permission needed", fontSize = 16.sp, fontWeight = FontWeight.Bold, color = CactusColors.Neutral800); Spacer(Modifier.height(8.dp)); Text("Open app settings -> Permissions -> enable Video and audio", fontSize = 12.sp, color = CactusColors.Neutral500, textAlign = TextAlign.Center); Spacer(Modifier.height(20.dp)); Button(onClick = { context.startActivity(Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS, Uri.fromParts("package", context.packageName, null)).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)) }, shape = RoundedCornerShape(50), colors = ButtonDefaults.buttonColors(containerColor = CactusColors.Black, contentColor = CactusColors.White)) { Icon(Icons.Filled.Settings, contentDescription = null, modifier = Modifier.size(16.dp)); Spacer(Modifier.width(8.dp)); Text("Open settings", fontSize = 14.sp, fontWeight = FontWeight.Bold) } } }
            uiState.permissionState == PermissionState.DENIED -> { Column(Modifier.fillMaxSize().padding(32.dp), horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.Center) { Box(Modifier.size(64.dp).clip(CircleShape).background(CactusColors.Neutral100), contentAlignment = Alignment.Center) { Icon(Icons.Filled.MusicVideo, contentDescription = null, tint = CactusColors.Neutral400, modifier = Modifier.size(28.dp)) }; Spacer(Modifier.height(20.dp)); Text("Media access needed", fontSize = 16.sp, fontWeight = FontWeight.Bold, color = CactusColors.Neutral800); Spacer(Modifier.height(20.dp)); Button(onClick = { permissionLauncher.launch(viewModel.requiredPermissions()) }, shape = RoundedCornerShape(50), colors = ButtonDefaults.buttonColors(containerColor = CactusColors.Black, contentColor = CactusColors.White)) { Text("Grant access", fontSize = 14.sp, fontWeight = FontWeight.Bold) } } }
            uiState.permissionState == PermissionState.GRANTED && uiState.isScanning -> { Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) { Column(horizontalAlignment = Alignment.CenterHorizontally) { CircularProgressIndicator(color = CactusColors.Black, strokeWidth = 2.dp, modifier = Modifier.size(40.dp)); Spacer(Modifier.height(16.dp)); Text("Scanning...", fontSize = 14.sp, fontWeight = FontWeight.SemiBold, color = CactusColors.Neutral700) } } }
            uiState.permissionState == PermissionState.GRANTED && videos.isEmpty() -> { Column(Modifier.fillMaxSize().padding(32.dp), horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.Center) { Box(Modifier.size(64.dp).clip(CircleShape).background(CactusColors.Neutral100), contentAlignment = Alignment.Center) { Icon(Icons.Filled.MusicVideo, contentDescription = null, tint = CactusColors.Neutral400, modifier = Modifier.size(28.dp)) }; Spacer(Modifier.height(20.dp)); Text("No videos found", fontSize = 16.sp, fontWeight = FontWeight.Bold, color = CactusColors.Neutral800); Spacer(Modifier.height(20.dp)); Button(onClick = { viewModel.scanMediaStore(); Toast.makeText(context, "Rescanning...", Toast.LENGTH_SHORT).show() }, shape = RoundedCornerShape(50), colors = ButtonDefaults.buttonColors(containerColor = CactusColors.Black, contentColor = CactusColors.White)) { Icon(Icons.Filled.Refresh, contentDescription = null, modifier = Modifier.size(16.dp)); Spacer(Modifier.width(8.dp)); Text("Rescan", fontSize = 14.sp, fontWeight = FontWeight.Bold) } } }
            else -> {
                Text("${videos.size} video${if (videos.size == 1) "" else "s"}", fontSize = 12.sp, fontWeight = FontWeight.Medium, color = CactusColors.Neutral400, modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 8.dp))
                LazyColumn(modifier = Modifier.fillMaxSize().padding(horizontal = 16.dp)) {
                    items(videos) { video ->
                        Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.fillMaxWidth().clickable(interactionSource = remember { MutableInteractionSource() }, indication = null) { onVideoClick(video) }.padding(vertical = 14.dp)) {
                            Box(modifier = Modifier.size(44.dp).clip(RoundedCornerShape(12.dp)).background(CactusColors.Neutral100), contentAlignment = Alignment.Center) { Icon(Icons.Filled.VideoFile, contentDescription = null, tint = CactusColors.Neutral500, modifier = Modifier.size(18.dp)) }
                            Spacer(Modifier.width(14.dp))
                            Column(modifier = Modifier.weight(1f)) {
                                Text(video.displayName, fontSize = 15.sp, fontWeight = FontWeight.SemiBold, color = CactusColors.Neutral900, maxLines = 1, overflow = TextOverflow.Ellipsis)
                                Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.padding(top = 4.dp)) {
                                    Text(FileSize.format(video.sizeBytes), fontSize = 12.sp, fontWeight = FontWeight.Medium, color = CactusColors.Neutral500)
                                    Text("  |  ", fontSize = 12.sp, color = CactusColors.Neutral300)
                                    val status = video.subtitleStatus
                                    if (status == com.cactus.app.data.model.SubtitleStatus.READY) { Text("Subtitle: Yes", fontSize = 12.sp, fontWeight = FontWeight.SemiBold, color = CactusColors.Neutral800) }
                                    else if (status == com.cactus.app.data.model.SubtitleStatus.FAILED) { Text("Subtitle: Failed", fontSize = 12.sp, fontWeight = FontWeight.Bold, color = CactusColors.Red500) }
                                    else { Text("Subtitle: No", fontSize = 12.sp, fontWeight = FontWeight.Medium, color = CactusColors.Neutral500) }
                                }
                            }
                            Spacer(Modifier.width(12.dp))
                            val sec = (video.durationMs / 1000).toInt(); Text("%02d:%02d".format(sec / 60, sec % 60), fontSize = 12.sp, fontWeight = FontWeight.Medium, color = CactusColors.Neutral500)
                            Spacer(Modifier.width(12.dp))
                            Icon(Icons.Filled.ChevronRight, contentDescription = null, tint = CactusColors.Neutral300, modifier = Modifier.size(14.dp))
                        }
                        HorizontalDivider(thickness = 1.dp, color = CactusColors.Neutral100)
                    }
                }
            }
        }
    }
}
private fun android.content.Context.findActivity(): android.app.Activity? { var ctx = this; while (ctx is android.content.ContextWrapper) { if (ctx is android.app.Activity) return ctx; ctx = ctx.baseContext }; return null }
